# For more information: https://laravel.com/docs/sail
version: '3'
services:
    db:
        image: mysql:5.7
        container_name: cooking_task_mysql
        environment:
            MYSQL_DATABASE: cooking_task
            MYSQL_USER: root
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3306:3306"
    php:
        image: webdevops/php:7.4
        container_name: cooking_task_php
        environment:
            PHP_UPLOAD_MAX_FILESIZE: 5000M
            PHP_POST_MAX_SIZE: 5000M
        volumes:
            - "./:/laravel"
        working_dir: '/laravel'
    nginx:
        depends_on:
            - php
        image: webdevops/nginx
        container_name: cooking_task_nginx
        environment:
            WEB_DOCUMENT_ROOT: /laravel/public
            WEB_DOCUMENT_INDEX: index.php
            WEB_PHP_SOCKET: php:9000
        volumes:
            - "./:/laravel"
        ports:
            - "80:80"
